/**
 * src/embed_tokenizer.ts is a second implementation of a tokenizer that already exists, and the
 * only thing that makes it worth having is producing the same ids as the first one. Reading it
 * cannot establish that. So it is checked against a frozen oracle generated by
 * @xenova/transformers -- a genuinely separate implementation, kept as a devDependency for this --
 * over a corpus of the inputs where a plausible implementation and a correct one part company.
 *
 * Regenerate both fixtures with `node scripts/regen_wordpiece_oracle.mjs`, which also holds the
 * corpus and the reason each entry is in it.
 *
 * The fixtures are gzipped and read back with node:zlib, so this test needs no network, no model
 * download and no optional dependency: it runs wherever CI runs and never skips.
 */
import * as fs from 'node:fs'
import * as path from 'node:path'
import * as zlib from 'node:zlib'
import { fileURLToPath } from 'node:url'

import { describe, expect, it } from 'vitest'

import { BertWordPiece, MAX_SEQUENCE_TOKENS, UnsupportedTokenizerError } from '../src/embed_tokenizer.js'

const fixtureDir = path.resolve(path.dirname(fileURLToPath(import.meta.url)), 'fixtures', 'wordpiece')

function readGzJson(name: string): unknown {
  return JSON.parse(zlib.gunzipSync(fs.readFileSync(path.join(fixtureDir, name))).toString('utf8'))
}

interface Oracle {
  model: string
  revision: string
  maxLength: number
  generatedBy: string
  records: { text: string; ids: number[] }[]
}

const spec = readGzJson('tokenizer.json.gz')
const oracle = readGzJson('oracle.json.gz') as Oracle
const tokenizer = new BertWordPiece(spec)

/** A short, readable label for a case whose text may be empty, long, or invisible. */
function label(text: string): string {
  const escaped = JSON.stringify(text)
  return escaped.length <= 60 ? escaped : `${escaped.slice(0, 57)}...`
}

describe('BertWordPiece against the reference implementation', () => {
  it('has an oracle with enough cases in it that an empty sweep cannot pass as a clean one', () => {
    expect(oracle.records.length).toBeGreaterThan(80)
    expect(oracle.maxLength).toBe(MAX_SEQUENCE_TOKENS)
    expect(oracle.generatedBy).toMatch(/^@xenova\/transformers@\d+\.\d+\.\d+$/)
  })

  it.each(oracle.records.map((r, i) => [i, label(r.text), r] as const))(
    'case %i matches the reference on %s',
    (_i, _label, record) => {
      expect(tokenizer.encode(record.text, oracle.maxLength)).toEqual(record.ids)
    },
  )

  // Per-case assertions above can each pass while the corpus as a whole has quietly stopped
  // covering something: the two cases that reach the truncation limit and the several that produce
  // a single [UNK] are the ones most likely to be edited into harmlessness.
  it('still covers truncation and unknown words at all', () => {
    const lengths = oracle.records.map((r) => r.ids.length)
    expect(lengths.filter((n) => n === MAX_SEQUENCE_TOKENS).length).toBeGreaterThanOrEqual(2)
    const withUnk = oracle.records.filter((r) => r.ids.includes(tokenizer.unkId))
    expect(withUnk.length).toBeGreaterThanOrEqual(3)
  })
})

describe('BertWordPiece behaviour that has no oracle case', () => {
  it('brackets every sequence with [CLS] and [SEP], including an empty one', () => {
    expect(tokenizer.encode('')).toEqual([tokenizer.clsId, tokenizer.sepId])
  })

  // The cut is taken after the markers are added, so a truncated sequence loses its [SEP]. That is
  // the reference's behaviour and is pinned here on purpose: it is the kind of detail a later
  // reader would "fix" without noticing it changes every long document's vector.
  it('cuts to the requested length and drops the closing marker rather than the text', () => {
    const ids = tokenizer.encode('tokenization '.repeat(400), 16)
    expect(ids.length).toBe(16)
    expect(ids[0]).toBe(tokenizer.clsId)
    expect(ids.at(-1)).not.toBe(tokenizer.sepId)
    expect(ids.slice(1)).toEqual(tokenizer.encode('tokenization '.repeat(400), 512).slice(1, 16))
  })

  it('keeps both markers when the text fits', () => {
    const ids = tokenizer.encode('tokenization', 16)
    expect(ids.length).toBeLessThan(16)
    expect(ids[0]).toBe(tokenizer.clsId)
    expect(ids.at(-1)).toBe(tokenizer.sepId)
  })

  it('refuses a length that cannot hold both markers rather than returning a malformed sequence', () => {
    expect(() => tokenizer.encode('anything', 1)).toThrow(RangeError)
    expect(() => tokenizer.encode('anything', 0)).toThrow(RangeError)
    expect(() => tokenizer.encode('anything', 2.5)).toThrow(RangeError)
    // Two is the smallest length that holds a sequence at all: the opening marker and one token,
    // which for an empty text is the closing marker and otherwise is the first word.
    expect(tokenizer.encode('', 2)).toEqual([tokenizer.clsId, tokenizer.sepId])
    expect(tokenizer.encode('anything', 2)).toEqual([tokenizer.clsId, tokenizer.encode('anything')[1]])
  })

  // The vocabulary is a Map for this reason. A plain object answers these from Object.prototype,
  // so the lookup "succeeds" with a function where a token id belongs.
  it.each(['constructor', 'toString', 'valueOf', 'hasOwnProperty', '__proto__'])(
    'returns integer ids for the prototype-chain word %s',
    (word) => {
      const ids = tokenizer.encode(word)
      expect(ids.every((id) => Number.isInteger(id))).toBe(true)
      expect(ids.length).toBeGreaterThan(2)
    },
  )
})

/** The pinned spec with one field changed, so each refusal test differs from the real one by exactly that field. */
function specWith(mutate: (spec: Record<string, unknown>) => void): unknown {
  const copy = JSON.parse(JSON.stringify(spec)) as Record<string, unknown>
  mutate(copy)
  return copy
}

describe('BertWordPiece refuses a spec it does not implement', () => {
  // Tokenizing an unsupported spec approximately produces vectors that are wrong by a little,
  // which is invisible until an index has been half-built with each. Refusing is the whole point.
  it.each([
    [
      'a different normalizer',
      (s: Record<string, unknown>) => {
        ;(s['normalizer'] as Record<string, unknown>)['type'] = 'NFC'
      },
      /normalizer\.type/,
    ],
    [
      'lowercasing turned off',
      (s: Record<string, unknown>) => {
        ;(s['normalizer'] as Record<string, unknown>)['lowercase'] = false
      },
      /normalizer\.lowercase/,
    ],
    [
      'accent stripping turned off',
      (s: Record<string, unknown>) => {
        ;(s['normalizer'] as Record<string, unknown>)['strip_accents'] = false
      },
      /strip_accents/,
    ],
    [
      'chinese character handling turned off',
      (s: Record<string, unknown>) => {
        ;(s['normalizer'] as Record<string, unknown>)['handle_chinese_chars'] = false
      },
      /handle_chinese_chars/,
    ],
    [
      'a different pre-tokenizer',
      (s: Record<string, unknown>) => {
        ;(s['pre_tokenizer'] as Record<string, unknown>)['type'] = 'ByteLevel'
      },
      /pre_tokenizer\.type/,
    ],
    [
      'a different model',
      (s: Record<string, unknown>) => {
        ;(s['model'] as Record<string, unknown>)['type'] = 'BPE'
      },
      /model\.type/,
    ],
    [
      'a different subword prefix',
      (s: Record<string, unknown>) => {
        ;(s['model'] as Record<string, unknown>)['continuing_subword_prefix'] = '@@'
      },
      /continuing_subword_prefix/,
    ],
    [
      'a different post-processor',
      (s: Record<string, unknown>) => {
        ;(s['post_processor'] as Record<string, unknown>)['type'] = 'RobertaProcessing'
      },
      /post_processor\.type/,
    ],
    [
      'a template that adds a token',
      (s: Record<string, unknown>) => {
        const post = s['post_processor'] as Record<string, unknown>
        const single = post['single'] as unknown[]
        post['single'] = [...single, { SpecialToken: { id: '[SEP]', type_id: 0 } }]
      },
      /post_processor\.single/,
    ],
    [
      'no [CLS] in the vocabulary',
      (s: Record<string, unknown>) => {
        delete ((s['model'] as Record<string, unknown>)['vocab'] as Record<string, unknown>)['[CLS]']
      },
      /\[CLS\]/,
    ],
    [
      'a vocabulary id that is not an integer',
      (s: Record<string, unknown>) => {
        ;((s['model'] as Record<string, unknown>)['vocab'] as Record<string, unknown>)['the'] = 'seven'
      },
      /model\.vocab/,
    ],
  ])('refuses %s', (_name, mutate, message) => {
    expect(() => new BertWordPiece(specWith(mutate))).toThrow(UnsupportedTokenizerError)
    expect(() => new BertWordPiece(specWith(mutate))).toThrow(message)
  })

  it('refuses text that is not a tokenizer.json at all', () => {
    expect(() => BertWordPiece.fromJson('{')).toThrow(UnsupportedTokenizerError)
    expect(() => BertWordPiece.fromJson('null')).toThrow(/not an object/)
    expect(() => BertWordPiece.fromJson('[]')).toThrow(/not an object/)
  })

  it('accepts the pinned spec through fromJson, so the refusals above are not refusing everything', () => {
    const json = zlib.gunzipSync(fs.readFileSync(path.join(fixtureDir, 'tokenizer.json.gz'))).toString('utf8')
    expect(BertWordPiece.fromJson(json).encode('hello world')).toEqual(tokenizer.encode('hello world'))
  })
})
