"""TypeScript/TSX/JS/JSX symbol extractor using tree_sitter_language_pack."""
from __future__ import annotations

import os
import re

import tree_sitter_language_pack as tlp

from ..parser import ImpExp, Ref, Section, Symbol
from . import common

# ---------------------------------------------------------------------------
# ABI special-case config (tunable via caller meta, not exposed in CLI yet)
# ---------------------------------------------------------------------------

_ABI_SIZE_THRESHOLD = 100_000       # bytes — files smaller than this are never ABI mode
_ABI_MAX_SYMBOLS = 500              # cap on symbols emitted for ABI files

# Top-level export extraction for ABI mode
_ABI_EXPORT_RE = re.compile(
    r"^export\s+(?:const|default|let|var|function|class|interface|type|enum)\s+"
    r"([A-Za-z_$][A-Za-z0-9_$]*)",
    re.MULTILINE,
)


def _is_abi_file(source: bytes, rel_path: str, threshold: int = _ABI_SIZE_THRESHOLD) -> bool:
    """Return True if this file should be treated as a generated ABI file."""
    if len(source) < threshold:
        return False

    # Filename heuristic
    name = os.path.basename(rel_path).lower()
    parts = rel_path.replace("\\", "/").split("/")
    if (
        name.endswith("abi.ts")
        or name.endswith("abi.d.ts")
        or name.endswith(".abi.ts")
        or (len(parts) >= 2 and parts[-2].lower() == "abi")
    ):
        return True

    # Content heuristic: check the first 2 KB for autogenerated headers
    head = source[:2048].decode("utf-8", errors="replace").lower()
    if any(marker in head for marker in ("// generated", "// auto-generated", "// autogenerated")):
        return True

    # Content heuristic: as const + many abi inputs/outputs
    text_sample = source[:8192].decode("utf-8", errors="replace")
    if "as const" in text_sample:
        n_inputs = text_sample.count('"inputs": [') + text_sample.count('"inputs":[')
        n_outputs = text_sample.count('"outputs": [') + text_sample.count('"outputs":[')
        if (n_inputs + n_outputs) > 5:
            return True

    return False


def _extract_abi(source: bytes) -> tuple[list[Symbol], list[Ref], list[ImpExp], list]:
    """Fast path for generated ABI files: index top-level exports only, no refs.

    Returns a 4-tuple matching the Extractor protocol (symbols, refs,
    imports/exports, sections). Sections is always empty for ABI files.
    """
    text = source.decode("utf-8", errors="replace")
    lines = text.splitlines()
    symbols: list[Symbol] = []
    seen: set[str] = set()

    for m in _ABI_EXPORT_RE.finditer(text):
        name = m.group(1)
        if name in seen:
            continue
        seen.add(name)
        # Compute line number from match position
        line = text[: m.start()].count("\n") + 1
        sig = lines[line - 1].rstrip()[:150] if line <= len(lines) else None
        symbols.append(Symbol(name=name, kind="abi_export", line=line, end_line=line, signature=sig))
        if len(symbols) >= _ABI_MAX_SYMBOLS:
            break

    return symbols, [], [], []

# ---------------------------------------------------------------------------
# Noise filter for call-site refs
# ---------------------------------------------------------------------------

_CALL_NOISE = frozenset([
    # JS builtins and globals
    "console", "Object", "Array", "Math", "JSON", "Promise", "Error",
    "Map", "Set", "WeakMap", "WeakSet", "Symbol", "Proxy", "Reflect",
    "String", "Number", "Boolean", "BigInt", "RegExp", "Date",
    "parseInt", "parseFloat", "isNaN", "isFinite", "encodeURIComponent",
    "decodeURIComponent", "encodeURI", "decodeURI", "setTimeout",
    "setInterval", "clearTimeout", "clearInterval", "fetch", "require",
    # Keywords that can be followed by (
    "if", "for", "while", "switch", "catch", "return", "throw",
    "typeof", "instanceof", "void", "delete", "yield", "await",
    "new", "super",
    # Single-char names
])

# Regex: identifier NOT preceded by . or -> that is immediately followed by (
_CALL_RE = re.compile(r"(?<![.\w])([A-Za-z_$][A-Za-z0-9_$]*)\s*\(")

# Regex to extract module path from import/export source line
_FROM_RE = re.compile(r"""from\s+['"]([^'"]+)['"]""")
_IMPORT_RE = re.compile(r"""^import\s+.*?['"]([^'"]+)['"]""")


def _extract_module(source_line: str) -> str:
    """Extract the module string from an import/export source text."""
    m = _FROM_RE.search(source_line)
    if m:
        return m.group(1)
    m = _IMPORT_RE.match(source_line.strip())
    if m:
        return m.group(1)
    return source_line.strip()


def _kind_str(structure_kind: object) -> str:
    """Convert StructureKind to our kind string."""
    return common.kind_str(structure_kind)


def _symbol_kind_str(sym_kind: object) -> str:
    """Convert SymbolKind to our kind string."""
    return common.sym_kind_str(sym_kind)


def _build_signature(source: bytes, item_span: object, body_span: object | None) -> str | None:
    """Extract header text (before body brace/colon) from raw source bytes."""
    if body_span is None:
        return None
    try:
        header = source[item_span.start_byte : body_span.start_byte]
        text = header.decode("utf-8", errors="replace").strip()
        # Truncate to 200 chars
        if len(text) > 200:
            text = text[:200]
        return text or None
    except (IndexError, AttributeError):
        return None


def _extract_refs(source: bytes) -> list[Ref]:
    """Extract call-site refs using regex on the source text."""
    refs: list[Ref] = []
    seen: set[tuple[str, int]] = set()
    text = source.decode("utf-8", errors="replace")
    for lineno, line in enumerate(text.splitlines(), 1):
        for m in _CALL_RE.finditer(line):
            name = m.group(1)
            if name in _CALL_NOISE or len(name) <= 1:
                continue
            key = (name, lineno)
            if key in seen:
                continue
            seen.add(key)
            refs.append(Ref(name=name, line=lineno, col=m.start(1), context=line.strip()[:120]))
    return refs


def extract(
    source: bytes,
    rel_path: str,
    *,
    meta: dict | None = None,
) -> tuple[list[Symbol], list[Ref], list[ImpExp], list[Section]]:
    """Extract symbols, refs, and imports/exports from a TS/TSX/JS/JSX file.

    ``meta`` is an optional dict supporting:
    - ``abi_size_threshold`` (int): override default 100_000-byte threshold
    - ``abi_max_symbols_per_file`` (int): override default 500-symbol cap
    """
    # Apply meta overrides for ABI config
    abi_threshold = _ABI_SIZE_THRESHOLD
    abi_max = _ABI_MAX_SYMBOLS
    if meta:
        abi_threshold = int(meta.get("abi_size_threshold", abi_threshold))
        abi_max = int(meta.get("abi_max_symbols_per_file", abi_max))

    # ABI fast path: skip expensive structure walk for huge generated type files
    if len(source) >= abi_threshold and _is_abi_file(source, rel_path, threshold=abi_threshold):
        syms, refs, ie, _ = _extract_abi(source)
        # Honour caller-supplied cap
        return syms[:abi_max], refs, ie, []

    # Detect language for tlp
    lower = rel_path.lower()
    if lower.endswith((".tsx", ".jsx")):
        lang = "tsx"
    elif lower.endswith(".ts"):
        lang = "typescript"
    else:
        lang = "javascript"

    text = source.decode("utf-8", errors="replace")
    cfg = tlp.ProcessConfig(
        language=lang,
        structure=True,
        imports=True,
        exports=True,
        symbols=True,
    )
    try:
        result = tlp.process(text, cfg)
    except Exception:
        return [], [], [], []

    symbols: list[Symbol] = []
    imp_exp: list[ImpExp] = []

    # --- symbols from structure (gives us methods via children) ---
    seen_names: set[tuple[str, int]] = set()

    def _add_symbol(item: object, parent_name: str | None = None) -> None:
        name: str = item.name  # type: ignore[attr-defined]
        span = item.span
        body_span = item.body_span if hasattr(item, "body_span") else None
        line = span.start_line + 1  # convert to 1-indexed
        end_line = span.end_line + 1
        kind = _kind_str(item.kind)
        sig = _build_signature(source, span, body_span)

        key = (name, line)
        if key not in seen_names:
            seen_names.add(key)
            symbols.append(
                Symbol(
                    name=name,
                    kind=kind,
                    line=line,
                    end_line=end_line,
                    signature=sig,
                    parent_name=parent_name,
                )
            )

        # Recurse into children (methods, nested functions)
        for child in item.children:  # type: ignore[attr-defined]
            _add_symbol(child, parent_name=name)

    for item in result.structure:
        _add_symbol(item)

    # --- additional symbols from SymbolInfo (catches type aliases, enums) ---
    for sym in result.symbols:
        name: str = sym.name  # type: ignore[attr-defined]
        span = sym.span
        line = span.start_line + 1
        kind = _symbol_kind_str(sym.kind)
        key = (name, line)
        if key not in seen_names:
            seen_names.add(key)
            symbols.append(
                Symbol(
                    name=name,
                    kind=kind,
                    line=line,
                    end_line=span.end_line + 1,
                    signature=None,
                    parent_name=None,
                )
            )

    # --- const/var from exports not captured above ---
    # exports like 'export const router = express()' aren't in structure;
    # also extract clean names for all export ImpExp entries
    _EXPORT_NAME_RES = [
        re.compile(r"export\s+(?:async\s+)?function\s*\*?\s*([A-Za-z_$][A-Za-z0-9_$]*)"),
        re.compile(r"export\s+(?:abstract\s+)?class\s+([A-Za-z_$][A-Za-z0-9_$]*)"),
        re.compile(r"export\s+interface\s+([A-Za-z_$][A-Za-z0-9_$]*)"),
        re.compile(r"export\s+(?:type\s+)?enum\s+([A-Za-z_$][A-Za-z0-9_$]*)"),
        re.compile(r"export\s+type\s+([A-Za-z_$][A-Za-z0-9_$]*)"),
        re.compile(r"export\s+(?:const|let|var)\s+([A-Za-z_$][A-Za-z0-9_$]*)"),
    ]

    for exp in result.exports:
        name_raw: str = exp.name  # type: ignore[attr-defined]
        span = exp.span
        line = span.start_line + 1

        # Attempt to extract a clean identifier from the statement text
        export_name: str | None = None
        for pattern in _EXPORT_NAME_RES:
            m = pattern.match(name_raw)
            if m:
                export_name = m.group(1)
                break

        if export_name is None:
            # Fallback: use first token after 'export'
            tokens = name_raw.strip().split()
            export_name = tokens[1] if len(tokens) > 1 else name_raw[:80]

        # For const/let/var exports not already in structure, add a symbol
        const_m = re.match(
            r"export\s+(?:const|let|var)\s+([A-Za-z_$][A-Za-z0-9_$]*)", name_raw
        )
        if const_m:
            cname = const_m.group(1)
            key = (cname, line)
            if key not in seen_names:
                seen_names.add(key)
                symbols.append(
                    Symbol(name=cname, kind="const", line=line, end_line=line, signature=None)
                )

        # Record as ImpExp
        kind_str = str(exp.kind).split(".")[-1].lower()
        ie_kind = "reexport" if kind_str == "reexport" else "export"
        imp_exp.append(ImpExp(kind=ie_kind, target=export_name, line=line))

    # --- imports ---
    for imp in result.imports:
        module = _extract_module(imp.source)
        line = imp.span.start_line + 1
        imp_exp.append(ImpExp(kind="import", target=module, line=line))

    # --- refs via regex ---
    refs = _extract_refs(source)

    return symbols, refs, imp_exp, []
