"""TypeScript/TSX/JS/JSX symbol extractor using tree_sitter_language_pack."""
from __future__ import annotations

import logging
import re
from os.path import basename

from ..parser import ImpExp, Ref, Section, Symbol
from . import common

_LOG = logging.getLogger("token_goat.languages.typescript")


# ---------------------------------------------------------------------------
# ABI special-case config (tunable via caller meta, not exposed in CLI yet)
# ---------------------------------------------------------------------------

_ABI_SIZE_THRESHOLD = 100_000       # bytes — files smaller than this are never ABI mode
_ABI_MAX_SYMBOLS = 500              # cap on symbols emitted for ABI files

# Top-level export extraction for ABI mode
_ABI_EXPORT_RE = re.compile(
    r"^export\s+(?:const|default|let|var|function|class|interface|type|enum)\s+"
    r"([A-Za-z_$][A-Za-z0-9_$]*)",
    re.MULTILINE,
)


def _is_abi_file(source: bytes, rel_path: str, threshold: int = _ABI_SIZE_THRESHOLD) -> bool:
    """Return True if this file should be treated as a generated ABI file.

    ABI files are large auto-generated TypeScript constants that encode Solidity
    contract interfaces.  Full tree-sitter parsing of these files is slow and
    produces thousands of near-useless symbols; the fast path in
    :func:`_extract_abi` handles them with a single regex pass instead.

    Three independent heuristics are checked in order (short-circuit on first
    match so we avoid reading the file content when the name already tells us):

    1. **Size gate** — files smaller than *threshold* bytes are never ABI mode,
       regardless of name or content.  This prevents mis-classifying tiny hand-
       written files that happen to share a name pattern.
    2. **Filename heuristic** — ``*abi.ts``, ``*abi.d.ts``, ``*.abi.ts``, or
       files inside an ``abi/`` directory are almost certainly generated.
    3. **Content heuristics** (read only when size + name both pass):
       - First 2 KB contains ``// generated`` / ``// auto-generated`` comment.
       - First 8 KB contains ``as const`` plus more than five ``"inputs":`` /
         ``"outputs":`` keys, which is the structural fingerprint of an ABI
         constant array.
    """
    if len(source) < threshold:
        return False

    # Filename heuristic
    name = basename(rel_path).lower()
    parts = rel_path.replace("\\", "/").split("/")
    if (
        name.endswith("abi.ts")
        or name.endswith("abi.d.ts")
        or name.endswith(".abi.ts")
        or (len(parts) >= 2 and parts[-2].lower() == "abi")
    ):
        return True

    # Content heuristic: check the first 2 KB for autogenerated headers
    head = source[:2048].decode("utf-8", errors="replace").lower()
    if any(marker in head for marker in ("// generated", "// auto-generated", "// autogenerated")):
        return True

    # Content heuristic: as const + many abi inputs/outputs
    text_sample = source[:8192].decode("utf-8", errors="replace")
    if "as const" in text_sample:
        n_inputs = text_sample.count('"inputs": [') + text_sample.count('"inputs":[')
        n_outputs = text_sample.count('"outputs": [') + text_sample.count('"outputs":[')
        if (n_inputs + n_outputs) > 5:
            return True

    return False


def _extract_abi(source: bytes) -> tuple[list[Symbol], list[Ref], list[ImpExp], list[Section]]:
    """Fast path for generated ABI files: index top-level exports only, no refs.

    Returns a 4-tuple matching the Extractor protocol (symbols, refs,
    imports/exports, sections). Sections is always empty for ABI files.
    """
    text = source.decode("utf-8", errors="replace")
    lines = text.splitlines()
    symbols: list[Symbol] = []
    seen: set[str] = set()

    for m in _ABI_EXPORT_RE.finditer(text):
        name = m.group(1)
        if name in seen:
            continue
        seen.add(name)
        # Compute line number from match position
        line = text[: m.start()].count("\n") + 1
        sig = lines[line - 1].rstrip()[:150] if line <= len(lines) else None
        symbols.append(Symbol(name=name, kind="abi_export", line=line, end_line=line, signature=sig))
        if len(symbols) >= _ABI_MAX_SYMBOLS:
            break

    return symbols, [], [], []

# ---------------------------------------------------------------------------
# Noise filter for call-site refs
# ---------------------------------------------------------------------------

_CALL_NOISE = frozenset([
    # JS builtins and globals
    "console", "Object", "Array", "Math", "JSON", "Promise", "Error",
    "Map", "Set", "WeakMap", "WeakSet", "Symbol", "Proxy", "Reflect",
    "String", "Number", "Boolean", "BigInt", "RegExp", "Date",
    "parseInt", "parseFloat", "isNaN", "isFinite", "encodeURIComponent",
    "decodeURIComponent", "encodeURI", "decodeURI", "setTimeout",
    "setInterval", "clearTimeout", "clearInterval", "fetch", "require",
    # Keywords that can be followed by (
    "if", "for", "while", "switch", "catch", "return", "throw",
    "typeof", "instanceof", "void", "delete", "yield", "await",
    "new", "super",
    # Single-char names
])

# Regex: identifier NOT preceded by . or -> that is immediately followed by (
_CALL_RE = re.compile(r"(?<![.\w])([A-Za-z_$][A-Za-z0-9_$]*)\s*\(")

# Regex to extract module path from import/export source line
_FROM_RE = re.compile(r"""from\s+['"]([^'"]+)['"]""")
_IMPORT_RE = re.compile(r"""^import\s+.*?['"]([^'"]+)['"]""")

# Export name extraction patterns — compiled once at module level so the
# per-call loop in extract() does not pay re.compile() overhead on every file.
_EXPORT_NAME_RES: list[re.Pattern[str]] = [
    re.compile(r"export\s+(?:async\s+)?function\s*\*?\s*([A-Za-z_$][A-Za-z0-9_$]*)"),
    re.compile(r"export\s+(?:abstract\s+)?class\s+([A-Za-z_$][A-Za-z0-9_$]*)"),
    re.compile(r"export\s+interface\s+([A-Za-z_$][A-Za-z0-9_$]*)"),
    re.compile(r"export\s+(?:type\s+)?enum\s+([A-Za-z_$][A-Za-z0-9_$]*)"),
    re.compile(r"export\s+type\s+([A-Za-z_$][A-Za-z0-9_$]*)"),
    re.compile(r"export\s+(?:const|let|var)\s+([A-Za-z_$][A-Za-z0-9_$]*)"),
]

# Compiled pattern for const/let/var export symbol extraction (used inside the
# export loop — must not be recreated per iteration).
_EXPORT_CONST_RE = re.compile(
    r"export\s+(?:const|let|var)\s+([A-Za-z_$][A-Za-z0-9_$]*)"
)


def _extract_module(source_line: str) -> str:
    """Extract the module string from an import/export source text."""
    m = _FROM_RE.search(source_line)
    if m:
        return m.group(1)
    m = _IMPORT_RE.match(source_line.strip())
    if m:
        return m.group(1)
    return source_line.strip()


def extract(
    source: bytes,
    rel_path: str,
    *,
    meta: dict[str, object] | None = None,
) -> tuple[list[Symbol], list[Ref], list[ImpExp], list[Section]]:
    """Extract symbols, refs, and imports/exports from a TS/TSX/JS/JSX file.

    ``meta`` is an optional dict supporting:
    - ``abi_size_threshold`` (int): override default 100_000-byte threshold
    - ``abi_max_symbols_per_file`` (int): override default 500-symbol cap
    """
    # Apply meta overrides for ABI config
    abi_threshold = _ABI_SIZE_THRESHOLD
    abi_max = _ABI_MAX_SYMBOLS
    if meta:
        raw_threshold = meta.get("abi_size_threshold")
        raw_max = meta.get("abi_max_symbols_per_file")
        try:
            if isinstance(raw_threshold, (int, float, str)):
                abi_threshold = int(raw_threshold)
            if isinstance(raw_max, (int, float, str)):
                abi_max = int(raw_max)
        except (TypeError, ValueError):
            _LOG.debug(
                "invalid ABI meta values (abi_size_threshold=%r, abi_max_symbols_per_file=%r); "
                "using defaults",
                raw_threshold,
                raw_max,
            )

    # ABI fast path: skip expensive structure walk for huge generated type files
    if len(source) >= abi_threshold and _is_abi_file(source, rel_path, threshold=abi_threshold):
        syms, refs, ie, _ = _extract_abi(source)
        # Honour caller-supplied cap
        return syms[:abi_max], refs, ie, []

    # Detect language for tlp
    lower = rel_path.lower()
    if lower.endswith((".tsx", ".jsx")):
        lang = "tsx"
    elif lower.endswith(".ts"):
        lang = "typescript"
    else:
        lang = "javascript"

    text = source.decode("utf-8", errors="replace")
    tlp, cfg = common.make_process_config(language=lang, exports=True)
    if tlp is None:
        return [], [], [], []
    try:
        result = tlp.process(text, cfg)
    except Exception:  # noqa: BLE001
        _LOG.debug("tree-sitter parse failed for typescript source: %s", rel_path, exc_info=True)
        return [], [], [], []

    symbols: list[Symbol] = []
    imp_exp: list[ImpExp] = []

    # --- symbols from structure (gives us methods via children) ---
    seen_names: set[tuple[str, int]] = set()
    _add_symbol = common.make_add_symbol(symbols, seen_names, source, language="typescript")
    for item in result.structure:
        _add_symbol(item)

    # --- additional symbols from SymbolInfo (catches type aliases, enums) ---
    common.add_symbol_info(symbols, seen_names, result.symbols, language="typescript")

    # --- const/var from exports not captured above ---
    # exports like 'export const router = express()' aren't in structure;
    # also extract clean names for all export ImpExp entries
    for exp in result.exports:
        name_raw: str = exp.name  # type: ignore[attr-defined]
        span = exp.span
        line = span.start_line + 1

        # Attempt to extract a clean identifier from the statement text.
        # _EXPORT_NAME_RES is compiled once at module level.
        export_name: str | None = None
        for pattern in _EXPORT_NAME_RES:
            m = pattern.match(name_raw)
            if m:
                export_name = m.group(1)
                break

        if export_name is None:
            # Fallback: use first token after 'export'
            tokens = name_raw.strip().split()
            export_name = tokens[1] if len(tokens) > 1 else name_raw[:80]

        # For const/let/var exports not already in structure, add a symbol.
        # _EXPORT_CONST_RE is compiled once at module level.
        const_m = _EXPORT_CONST_RE.match(name_raw)
        if const_m:
            cname = const_m.group(1)
            key = (cname, line)
            if key not in seen_names:
                seen_names.add(key)
                symbols.append(
                    Symbol(name=cname, kind="const", line=line, end_line=line, signature=None)
                )

        # Record as ImpExp
        kind_str = str(exp.kind).split(".")[-1].lower()
        ie_kind = "reexport" if kind_str == "reexport" else "export"
        imp_exp.append(ImpExp(kind=ie_kind, target=export_name, line=line))

    # --- imports ---
    common.add_imports(
        imp_exp,
        result.imports,
        lambda imp: _extract_module(imp.source),  # type: ignore[attr-defined]
    )

    # --- refs via regex ---
    refs: list[Ref] = common.extract_refs_from_source(source, _CALL_RE, _CALL_NOISE)  # type: ignore[no-redef]

    return symbols, refs, imp_exp, []
