// Subprocess wrapper invoked by `token-goat compress` to run user commands.
//
// The pre-bash hook rewrites a Bash tool call from
//     pytest -v tests/
// to
//     token-goat compress --filter pytest --cmd 'pytest -v tests/'
// When the harness executes the rewritten command, control lands here via
// `run()`: it runs the original command through the system shell, captures
// stdout and stderr, applies the requested filter, prints the compressed view
// with a one-line savings marker, records the byte/token savings, and exits
// with the *original* exit code so shell chaining (`cmd && next`) still works.
//
// `shell: true` is deliberate — the original command may use pipes, redirects,
// globs, env expansion, or chaining the user wrote intentionally. The command
// string was generated by the agent/user, not an untrusted source, and the
// hook's `detectFromCommand` already rejected pipelines/subshells before
// wrapping, so the wrapper adds no further escaping.

import { spawnSync } from 'node:child_process'
import * as os from 'node:os'

import { loadConfig } from './config.js'
import { recordStat } from './stats.js'
import {
  type CompressedOutput,
  type ToolFilter,
  capTokens,
  compressOutput,
  filterByName,
  selectFilter,
  shlexSplit,
} from './tool_filters/index.js'

/** Default wall-clock timeout for the wrapped subprocess, in seconds. */
export const DEFAULT_TIMEOUT_SECONDS = 600

/** Per-process capture cap (stdout and stderr each). Beyond this the child is
 * killed and an overflow marker is appended — 32 MiB covers any real command. */
export const MAX_CAPTURE_BYTES = 32 * 1024 * 1024

/** Minimum bytes saved before a stat row is worth writing (skips noise rows). */
const MIN_RECORD_STAT_BYTES = 32

/** Options for {@link run}. */
export interface RunOptions {
  filterName?: string | undefined
  timeout?: number
  cwd?: string | undefined
  env?: NodeJS.ProcessEnv | undefined
  compressionProfile?: string | undefined
  maxTokens?: number
  writeStdout?: (s: string) => void
  writeStderr?: (s: string) => void
}

/** Look up the filter by name first, falling back to argv-based dispatch. */
function resolveFilter(command: string, filterName: string | undefined): ToolFilter | null {
  if (filterName) {
    const named = filterByName(filterName)
    if (named !== null) return named
    // Unknown name — fall through to auto-detect rather than failing.
  }
  let argv: string[]
  try {
    argv = shlexSplit(command)
  } catch {
    return null
  }
  return selectFilter(argv)
}

/** Map a Node signal name to `128 + signum`, the shell exit convention. */
function signalExitCode(signal: NodeJS.Signals): number {
  const num = (os.constants.signals as Record<string, number>)[signal]
  return 128 + (num ?? 0)
}

/**
 * Resolve the effective compression profile: explicit argument wins; otherwise
 * read from config, treating `"auto"` (no harness detection in the wrapper) as
 * `"balanced"`. Config errors fall back to `"balanced"`.
 */
function resolveProfile(explicit: string | undefined): string {
  if (explicit) return explicit
  try {
    const p = loadConfig().compression.profile
    return p && p !== 'auto' ? p : 'balanced'
  } catch {
    return 'balanced'
  }
}

/**
 * Run *command* through the system shell, compress its output, and return the
 * wrapped subprocess's exit code (124 on wrapper-induced timeout, `128 + signum`
 * when killed by a signal). When no filter applies the command is streamed
 * through unchanged so the cost is limited to one subprocess fork.
 */
export function run(command: string, opts: RunOptions = {}): number {
  const timeout = opts.timeout ?? DEFAULT_TIMEOUT_SECONDS
  const filter = resolveFilter(command, opts.filterName)
  if (filter === null) {
    return passthrough(command, timeout, opts.cwd, opts.env)
  }
  return wrapAndCompress(command, filter, timeout, resolveProfile(opts.compressionProfile), opts)
}

/**
 * Run *command* raw with no compression, inheriting the parent's stdio and
 * returning its exit code. Used by `compress --no-compress` to debug the
 * wrapper by streaming output straight through.
 */
export function runRaw(command: string, timeout: number = DEFAULT_TIMEOUT_SECONDS): number {
  return passthrough(command, timeout, undefined, undefined)
}

/** Run *command* with no compression, inheriting the parent's stdio. */
function passthrough(
  command: string,
  timeout: number,
  cwd: string | undefined,
  env: NodeJS.ProcessEnv | undefined,
): number {
  const result = spawnSync(command, {
    shell: true,
    stdio: 'inherit',
    timeout: timeout * 1000,
    cwd,
    env,
  })
  if (isTimeout(result.error)) return 124
  if (result.status !== null) return result.status
  if (result.signal) return signalExitCode(result.signal)
  return 0
}

/** True when a spawnSync error indicates the wrapper-imposed timeout fired. */
function isTimeout(error: Error | undefined): boolean {
  return !!error && (error as NodeJS.ErrnoException).code === 'ETIMEDOUT'
}

/** Decode captured bytes as UTF-8 with replacement; null/undefined → empty. */
function decode(buf: Buffer | string | null | undefined): string {
  if (buf == null) return ''
  return typeof buf === 'string' ? buf : buf.toString('utf8')
}

/** Run *command* with output capture, apply *filter*, print the compressed view. */
function wrapAndCompress(
  command: string,
  filter: ToolFilter,
  timeout: number,
  profile: string,
  opts: RunOptions,
): number {
  const writeStdout = opts.writeStdout ?? ((s: string) => process.stdout.write(s))
  const start = Date.now()
  const result = spawnSync(command, {
    shell: true,
    stdio: ['ignore', 'pipe', 'pipe'],
    timeout: timeout * 1000,
    maxBuffer: MAX_CAPTURE_BYTES,
    cwd: opts.cwd,
    env: opts.env,
  })

  const timedOut = isTimeout(result.error)
  const overflowed = !!result.error && (result.error as NodeJS.ErrnoException).code === 'ENOBUFS'
  let stdoutText = decode(result.stdout)
  let stderrText = decode(result.stderr)
  if (overflowed) {
    stdoutText += `\n[token-goat: capture capped at ${MAX_CAPTURE_BYTES / (1024 * 1024)} MiB]`
  }

  let exitCode: number
  if (timedOut) {
    exitCode = 124
    stderrText = (stderrText ? stderrText + '\n' : '') + `[token-goat: command exceeded ${timeout}s timeout and was killed]`
  } else if (result.status !== null) {
    exitCode = result.status
  } else if (result.signal) {
    exitCode = signalExitCode(result.signal)
  } else {
    exitCode = 0
  }

  let argv: string[]
  try {
    argv = shlexSplit(command)
  } catch {
    argv = [command]
  }

  const compressed = compressOutput(filter, stdoutText, stderrText, exitCode, argv, {
    compressionProfile: profile,
  })
  // Apply the pressure-scaled token cap to the body BEFORE appending the marker
  // so the savings marker survives truncation and stays visible to the agent.
  let text = compressed.text
  const maxTokens = opts.maxTokens ?? 0
  if (maxTokens > 0) text = capTokens(text, maxTokens)
  const marker = compressed.withMarker().slice(compressed.text.length) // "" when no savings
  const body = text + marker
  writeStdout(body.endsWith('\n') ? body : body + '\n')

  recordSavings(compressed, Date.now() - start)
  return exitCode
}

/** Best-effort: record the savings stat. recordStat already swallows DB errors. */
function recordSavings(result: CompressedOutput, _elapsedMs: number): void {
  if (result.bytesSaved < MIN_RECORD_STAT_BYTES) return
  recordStat(`bash_compress:${result.filterName}`, result.bytesSaved, result.tokensSaved)
}
