// Subprocess wrapper invoked by `token-goat compress` to run user commands.
//
// The pre-bash hook rewrites a Bash tool call from pytest -v tests/ to token-goat compress --filter pytest --cmd 'pytest -v tests/' When the harness executes the rewritten command, control lands here via `run()`: it runs the original command through the system shell, captures stdout and stderr, applies the requested filter, prints the compressed view with a one-line savings marker, records the byte/token savings, and exits with the *original* exit code so shell chaining (`cmd && next`) still works.
//
// Running through a shell is deliberate — the original command may use pipes, redirects, globs, env expansion, or chaining the user wrote intentionally. The command string was generated by the agent/user, not an untrusted source, and the hook's `detectFromCommand` already rejected pipelines/subshells before wrapping, so the wrapper adds no further escaping. The shell is chosen by wrappedShell(): /bin/sh on POSIX, the harness's Git-Bash on Windows (not cmd.exe, which cannot run the bash the harness wrote) — see src/shell.ts.

import { spawn, spawnSync } from 'node:child_process'
import * as os from 'node:os'

import { storeBashOutputSync } from './bash_output_cache.js'
import { loadConfig } from './config.js'
import { deliveredOutputBytes } from './delivery_cap.js'
import { wrappedShell, resolvePowerShell } from './shell.js'
import { recordStat } from './stats.js'
import { PassthroughFilter } from './tool_filters/generic.js'
import {
  type CompressedOutput,
  type ToolFilter,
  compressedTokensSaved,
  capTokens,
  deliverCompressed,
  dispatchArgv,
  filterByName,
  selectFilter,
  shlexSplit,
} from './tool_filters/index.js'

/** Default wall-clock timeout for the wrapped subprocess, in seconds. */
export const DEFAULT_TIMEOUT_SECONDS = 600

/** Per-process capture cap (stdout and stderr each). Beyond this the child is killed and an overflow marker is appended — 32 MiB covers any real command. */
export const MAX_CAPTURE_BYTES = 32 * 1024 * 1024

/** Minimum bytes saved before a stat row is worth writing (skips noise rows). */
const MIN_RECORD_STAT_BYTES = 32

/** First heartbeat delay for a long, quiet compressed command; each subsequent one doubles (15s, 30s, 60s, 120s, ...) so a 10-minute quiet run adds a handful of lines, not dozens. Injectable via {@link RunOptions.heartbeatIntervalMs} for tests; the shipping path always leaves it at this default. */
export const DEFAULT_HEARTBEAT_INTERVAL_MS = 15_000

/** Options for {@link run}. */
export interface RunOptions {
  filterName?: string | undefined
  timeout?: number
  cwd?: string | undefined
  env?: NodeJS.ProcessEnv | undefined
  compressionProfile?: string | undefined
  maxTokens?: number
  /** Printed after the recall line when the output was cut, by `maxTokens` or by the filter's own line and byte limits:the narrower command that answers the question, since a capped dump is exactly the case where running it again is the wrong next move. */
  capHint?: string | undefined
  writeStdout?: (s: string) => void
  writeStderr?: (s: string) => void
  quietSuccess?: boolean | undefined
  nativeShell?: boolean | undefined
  shellType?: 'bash' | 'pwsh' | 'powershell' | 'native' | string | undefined
  heartbeatIntervalMs?: number
}

/** Accumulates chunks up to `cap` total bytes, then silently drops the rest and flags `overflowed` so the caller can kill the child and append a truncation marker -- the async-spawn equivalent of `spawnSync`'s `maxBuffer` + `ENOBUFS`. */
class CaptureSink {
  private readonly chunks: Buffer[] = []
  private bytes = 0
  overflowed = false

  constructor(private readonly cap: number) {}

  push(chunk: Buffer): void {
    if (this.overflowed) return
    this.bytes += chunk.length
    if (this.bytes > this.cap) {
      this.overflowed = true
      return
    }
    this.chunks.push(chunk)
  }

  text(): string {
    return decode(Buffer.concat(this.chunks))
  }
}

/** Drives a doubling heartbeat timer from `startTime`: fires `write(elapsedSeconds)` after `intervalMs`, `intervalMs * 2`, `intervalMs * 4`, ... `onOutput()` resets the schedule back to `intervalMs`, so a chatty command that keeps producing output never sees a heartbeat at all -- only a genuinely quiet stretch does. */
function scheduleHeartbeat(startTime: number, intervalMs: number, write: (elapsedSeconds: number) => void): { onOutput: () => void; stop: () => void } {
  let interval = intervalMs
  let timer: ReturnType<typeof setTimeout> | undefined
  const arm = (): void => {
    timer = setTimeout(() => {
      write(Math.round((Date.now() - startTime) / 1000))
      interval *= 2
      arm()
    }, interval)
    timer.unref()
  }
  arm()
  return {
    onOutput: (): void => {
      interval = intervalMs
      if (timer !== undefined) clearTimeout(timer)
      arm()
    },
    stop: (): void => {
      if (timer !== undefined) clearTimeout(timer)
    },
  }
}

/** Look up the filter by name first, falling back to argv-based dispatch, and return the argv that filter was chosen from alongside it. Selection and argv derivation share one `shlexSplit` + `dispatchArgv` here on purpose: they used to be computed independently (here and again in `wrapAndCompress`), so on a `cd DIR && grep ...` command the filter was picked from the peeled tokens while `compressOutput` still received an argv starting with `cd` -- every argv-reading filter then read the wrong flags/pattern/subcommand. */
export function resolveFilter(
  command: string,
  filterName: string | undefined,
  cwd: string | undefined,
): { filter: ToolFilter | null; argv: string[] } {
  // No caller-supplied cwd means the command runs in this process's own directory, which is the one whose package.json `npm test` / `yarn lint` resolves against. Leaving it undefined here left `resolvePackageManagerScript` unreachable from the CLI entirely, so a wrapped `compress -c "yarn lint"` fell through to the generic filter while the pre-hook, which does pass a cwd, picked the script's real one.
  const effectiveCwd = cwd ?? process.cwd()
  let split: string[] | null
  try {
    split = shlexSplit(command)
  } catch {
    split = null
  }
  // Same fallback wrapAndCompress used when the command is unsplittable: hand the filter the raw command as a single token.
  const argv = split === null ? [command] : dispatchArgv(split, effectiveCwd).argv
  if (filterName) {
    const named = filterByName(filterName)
    if (named !== null) return { filter: named, argv }
    // Unknown name — fall through to auto-detect rather than failing.
  }
  if (split === null) return { filter: null, argv }
  return { filter: selectFilter(split, effectiveCwd), argv }
}

// Shared spawnSync options for the two run paths: timeout, cwd. Each caller adds its own stdio (and maxBuffer for the capture path) plus the file/args/shell/env from spawnTarget.
function baseSpawnOptions(timeout: number, cwd: string | undefined) {
  return { timeout: timeout * 1000, cwd }
}

// Resolve what spawnSync should actually invoke, plus any extra env needed to carry the command text intact. On Windows there is no real argv array at the OS level: CreateProcess always takes one command-line string, and Git-Bash's MSYS runtime reconstructs its own argv from that string with its own backslash-unescaping rules -- which fire the same way whether Node built the string via spawnSync's `shell` option or via a literal `['-c', command]` argv element, silently dropping a level of backslashes (`\\` becomes `\`) either way. Environment variables cross the process boundary as raw bytes with no command-line parsing at all, so carrying the command through `TG_CMD` and running `eval "$TG_CMD"` sidesteps the mangling entirely.
function spawnTarget(
  command: string,
  nativeShell: boolean | undefined,
  shellType?: string | undefined,
): { file: string; args: string[]; shell: boolean; cmdEnv?: NodeJS.ProcessEnv } {
  if (shellType === 'pwsh' || shellType === 'powershell') {
    const ps = resolvePowerShell()
    return {
      file: ps,
      args: [
        '-NoProfile',
        '-NonInteractive',
        '-Command',
        '$c = $env:TG_CMD; Remove-Item Env:\\TG_CMD -ErrorAction SilentlyContinue; [scriptblock]::Create($c).Invoke(); if ($LASTEXITCODE -ne $null -and $LASTEXITCODE -ne 0) { exit $LASTEXITCODE }',
      ],
      shell: false,
      cmdEnv: { TG_CMD: command },
    }
  }
  const shell = nativeShell || shellType === 'native' ? true : wrappedShell()
  if (typeof shell === 'string') return { file: shell, args: ['-c', 'eval "$TG_CMD"'], shell: false, cmdEnv: { TG_CMD: command } }
  return { file: command, args: [], shell }
}

/** Merge the base env with any command-carrying env spawnTarget produced, without dropping the parent's environment when *env* itself is undefined (spawnSync's `env` option, once set, replaces rather than extends `process.env`). */
function mergeSpawnEnv(env: NodeJS.ProcessEnv | undefined, cmdEnv: NodeJS.ProcessEnv | undefined): NodeJS.ProcessEnv | undefined {
  return cmdEnv ? { ...(env ?? process.env), ...cmdEnv } : env
}

/** Map a Node signal name to `128 + signum`, the shell exit convention. */
function signalExitCode(signal: NodeJS.Signals): number {
  const num = (os.constants.signals as Record<string, number>)[signal]
  return 128 + (num ?? 0)
}

/** Resolve the effective compression profile: explicit argument wins; otherwise read from config, treating `"auto"` (no harness detection in the wrapper) as `"balanced"`. Config errors fall back to `"balanced"`. */
function resolveProfile(explicit: string | undefined): string {
  if (explicit) return explicit
  try {
    const p = loadConfig().compression.profile
    return p && p !== 'auto' ? p : 'balanced'
  } catch {
    return 'balanced'
  }
}

/** Resolve the bash_compress line/byte compression caps from config, falling back to the tool-filter layer's own built-in defaults on load failure. */
function resolveCompressLimits(): { maxLines: number; maxBytes: number } {
  try {
    const bc = loadConfig().bash_compress
    return { maxLines: bc.max_lines, maxBytes: bc.max_bytes }
  } catch {
    return { maxLines: 1000, maxBytes: 64 * 1024 }
  }
}

/** Run *command* through the system shell, compress its output, and return the wrapped subprocess's exit code (124 on wrapper-induced timeout, `128 + signum` when killed by a signal). When no filter applies the command is streamed through unchanged so the cost is limited to one subprocess fork. */
export async function run(command: string, opts: RunOptions = {}): Promise<number> {
  const timeout = opts.timeout ?? DEFAULT_TIMEOUT_SECONDS
  const { filter, argv } = resolveFilter(command, opts.filterName, opts.cwd)
  if (filter === null) {
    // No tool filter matches this command. Ordinarily that means streaming it through raw is cheapest (one subprocess fork, no capture). But when the caller asked for a `--max-tokens` cap or `--quiet-success`, raw passthrough would silently bypass it — `passthrough()` uses `stdio: 'inherit'` and never sees the output. Route through the capture-and-compress path with an identity filter instead, so the options apply.
    if ((opts.maxTokens ?? 0) > 0 || opts.quietSuccess) {
      return wrapAndCompress(command, argv, new PassthroughFilter(), timeout, resolveProfile(opts.compressionProfile), opts)
    }
    return passthrough(command, timeout, opts.cwd, opts.env, opts.nativeShell, opts.shellType)
  }
  return wrapAndCompress(command, argv, filter, timeout, resolveProfile(opts.compressionProfile), opts)
}

/** Run *command* raw with no compression, inheriting the parent's stdio and returning its exit code. Used by `compress --no-compress` to debug the wrapper by streaming output straight through. */
export function runRaw(
  command: string,
  timeout: number = DEFAULT_TIMEOUT_SECONDS,
  nativeShell?: boolean,
  shellType?: string,
): number {
  return passthrough(command, timeout, undefined, undefined, nativeShell, shellType)
}

/** Run *command* with no compression, inheriting the parent's stdio. */
function passthrough(
  command: string,
  timeout: number,
  cwd: string | undefined,
  env: NodeJS.ProcessEnv | undefined,
  nativeShell?: boolean,
  shellType?: string,
): number {
  const { file, args, shell, cmdEnv } = spawnTarget(command, nativeShell, shellType)
  const result = spawnSync(file, args, {
    ...baseSpawnOptions(timeout, cwd),
    shell,
    env: mergeSpawnEnv(env, cmdEnv),
    stdio: 'inherit',
  })
  if (isTimeout(result.error)) return 124
  if (result.status !== null) return result.status
  if (result.signal) return signalExitCode(result.signal)
  return 0
}

/** True when a spawnSync error indicates the wrapper-imposed timeout fired. */
function isTimeout(error: Error | undefined): boolean {
  return !!error && (error as NodeJS.ErrnoException).code === 'ETIMEDOUT'
}

/** Decode captured bytes as UTF-8 with replacement; null/undefined → empty. */
function decode(buf: Buffer | string | null | undefined): string {
  if (buf == null) return ''
  return typeof buf === 'string' ? buf : buf.toString('utf8')
}

/** Run *command* with output capture, apply *filter*, print the compressed view. `argv` is the dispatch argv the filter was selected from (see {@link resolveFilter}), NOT re-derived here. */
async function wrapAndCompress(
  command: string,
  argv: string[],
  filter: ToolFilter,
  timeout: number,
  profile: string,
  opts: RunOptions,
): Promise<number> {
  const writeStdout = opts.writeStdout ?? ((s: string) => process.stdout.write(s))
  const writeStderr = opts.writeStderr ?? ((s: string) => process.stderr.write(s))
  const startTime = Date.now()
  const { file, args, shell, cmdEnv } = spawnTarget(command, opts.nativeShell, opts.shellType)
  const stdoutSink = new CaptureSink(MAX_CAPTURE_BYTES)
  const stderrSink = new CaptureSink(MAX_CAPTURE_BYTES)
  let timedOut = false
  let overflowed = false

  // Async spawn (not spawnSync) is required for the heartbeat below: a blocking spawnSync call never lets the event loop tick, so no timer could ever fire while the child is still running -- this is the actual root cause of `token-goat compress` looking hung on a long, quiet command, not just a missing print statement.
  const child = spawn(file, args, { cwd: opts.cwd, shell, env: mergeSpawnEnv(opts.env, cmdEnv), stdio: ['ignore', 'pipe', 'pipe'] })
  const heartbeat = scheduleHeartbeat(startTime, opts.heartbeatIntervalMs ?? DEFAULT_HEARTBEAT_INTERVAL_MS, (elapsed) => {
    writeStderr(`[token-goat compress] still running, ${elapsed}s elapsed\n`)
  })
  const timeoutHandle = setTimeout(() => {
    timedOut = true
    child.kill()
  }, timeout * 1000)

  const onData = (sink: CaptureSink) => (chunk: Buffer): void => {
    heartbeat.onOutput()
    sink.push(chunk)
    if (sink.overflowed) {
      overflowed = true
      child.kill()
    }
  }
  child.stdout?.on('data', onData(stdoutSink))
  child.stderr?.on('data', onData(stderrSink))

  const { code, signal } = await new Promise<{ code: number | null; signal: NodeJS.Signals | null }>((resolve) => {
    child.on('close', (code, signal) => resolve({ code, signal }))
  })
  heartbeat.stop()
  clearTimeout(timeoutHandle)

  let stdoutText = stdoutSink.text()
  let stderrText = stderrSink.text()
  if (overflowed) {
    stdoutText += `\n[token-goat: capture capped at ${MAX_CAPTURE_BYTES / (1024 * 1024)} MiB]`
  }

  let exitCode: number
  if (timedOut) {
    exitCode = 124
    stderrText = (stderrText ? stderrText + '\n' : '') + `[token-goat: command exceeded ${timeout}s timeout and was killed]`
  } else if (code !== null) {
    exitCode = code
  } else if (signal) {
    exitCode = signalExitCode(signal)
  } else {
    exitCode = 0
  }

  if (opts.quietSuccess && exitCode === 0) {
    const duration = ((Date.now() - startTime) / 1000).toFixed(1) + 's'
    const fullRaw = (stdoutText + (stderrText ? '\n' + stderrText : '')).trim()
    const id = storeBashOutputSync(command, fullRaw, 0, opts.cwd ?? null)
    const summary = `[tg: ok] ${command} (${duration}, recall: token-goat bash-output ${id})\n`
    writeStdout(summary)
    return 0
  }

  const limits = resolveCompressLimits()
  // The net-benefit gate lives in `deliverCompressed`: a rewrite whose bytesSaved doesn't clear the marker's own cost plus the configured floor destabilises the bytes (breaks provider prefix caching) for a saving too small to be worth it, so below the floor that function returns the ORIGINAL streams with no marker -- exactly as though no filter had matched. `token-goat bench` measures delivery through the same function, so a benchmark cannot drift from what actually ships.
  const { applied, marker, compressed, text: delivered } = deliverCompressed(filter, stdoutText, stderrText, exitCode, argv, {
    compressionProfile: profile,
    maxLines: limits.maxLines,
    maxBytes: limits.maxBytes,
  })
  // Apply the pressure-scaled token cap to the body BEFORE appending the marker so the savings marker survives truncation and stays visible to the agent.
  let text = delivered
  const maxTokens = opts.maxTokens ?? 0
  if (maxTokens > 0) text = capTokens(text, maxTokens)
  const capped = text !== delivered
  let body = text + marker
  // A cap that cut the output is a loss the same as a filter that did, so it gets the same recall. Keyed on `applied` alone, a passthrough run capped to 2,000 tokens dropped the rest with nothing to recover it from.
  if (applied || capped) {
    // The marker's own notice names TOKEN_GOAT_BASH_COMPRESS as the way to disable compression, but that env var has to be set in the environment that launches the harness, not inline in this same command -- the hook process reads its own environment, never the wrapped command's, so an inline prefix here can never reach it. A recall of the untruncated bytes is the actionable follow-up, so store them the same way the compound post-hook path already does and point at it.
    const fullRaw = (stdoutText + (stderrText ? '\n' + stderrText : '')).trim()
    const recallId = storeBashOutputSync(command, fullRaw, exitCode, opts.cwd ?? null)
    body += '\n[token-goat] full output: bash-output ' + recallId + ' --full'
    if (opts.capHint) body +='\n[token-goat] ' + opts.capHint
  }
  writeStdout(body.endsWith('\n') ? body : body + '\n')

  if (applied) recordSavings(compressed)
  return exitCode
}

/** Best-effort: record the savings stat. recordStat already swallows DB errors. Measured against the DELIVERED size, not the original. The harness caps how much of a Bash result reaches the model (see {@link deliveredOutputBytes}), so compressing a 30 MB output to 8 KB spares it at most `cap - 8 KB`, never 30 MB. Booking `result.bytesSaved` credited output the model was never going to be shown. The APPLY decision above deliberately still runs on the uncapped bytes. The two answer different questions: the gate asks whether a compressed body beats the harness's arbitrary head-truncation of the same output (it does -- the model sees a coherent summary instead of the first 20 KB), while this figure asks how many tokens were actually spared. Capping the gate would suppress the rewrites with the most to offer, which is a behaviour change this accounting fix must not make. */
function recordSavings(result: CompressedOutput): void {
  const delivered = deliveredOutputBytes(result.originalBytes)
  const bytesSaved = Math.max(0, delivered - result.compressedBytes)
  if (bytesSaved < MIN_RECORD_STAT_BYTES) return
  recordStat(`bash_compress:${result.filterName}`, bytesSaved, compressedTokensSaved(bytesSaved))
}
