/**
 * Compact CLI help generation.
 */

export function generateCompactHelp(): string {
  const lines = [
    'Usage: token-goat [options] [command]',
    '',
    'Surgical token-reduction companion for AI coding agents',
    '',
    'Options:',
    '  -v, --version                   print the token-goat version',
    '  --cwd <path>                    run as if invoked from this directory',
    '  --notice <text>                 print this line before the command\'s own output',
    '  -h, --help                      display help for command',
    '',
    'Reads: symbol, read, brief, section, semantic, skeleton, outline, refs, scope,',
    '  similar, context-for, call-chain, impact, callers, dead, test-for, locate',
    '',
    'Analysis: arch, affected, blame, deps, types, coverage-gaps, changed, diff, log,',
    '  exports, imports, find, grep',
    '',
    'File Formats: pdf-meta, pdf-outline, pdf-extract, pdf-locate, xlsx-sheets,',
    '  xlsx-head, xlsx-columns, xlsx-query, xlsx-range, yaml-outline, yaml-query,',
    '  json-outline, json-query, xml-outline, xml-query, html-outline, html-query,',
    '  html-lint, docx-outline, docx-tables, docx-text, pptx-outline, pptx-slide, pptx-text,',
    '  pptx-notes',
    '',
    'Index & Search: index, map, reconcile, doctor, commands, ask, answer, pack, tokens,',
    '  budget, failures, todo, trace, logfold, lockdeps, dep-docs, recent, hot,',
    '  baseline, cost, coverage-report-gaps, clean-cache,',
    '  cache-audit, reclaim-index, project',
    '',
    'Session: stats, waste, session-outline, session-audit, session-slice,',
    '  session-summary, context-stats, bootstrap-audit, memory, hint-stats,',
    '  session-schema, mcp-audit, audit',
    '',
    'Skills: skill-body, skill-compact, skill-list, skill-size, skill-history,',
    '  skill-diff, skill-section',
    '',
    'Compression: compress-text, retrieve, handoff-create, handoff-resolve,',
    '  compress, recall, bash-output, web-output, mcp-output, bench',
    '',
    'Config & Integration: install, uninstall, upgrade, mcp-serve, mcp-status, hook,',
    '  bridges-status, worker, statusline, version, config, config-get,',
    '  capabilities, help',
    '',
    'Data: note, note-add, note-get, note-list, describe, sqlite-query,',
    '  sqlite-tables, sqlite-schema, csv-profile, csv-query',
    '',
    'Utils: ignores, bash-history, web-history, history, openapi-op, openapi-outline,',
    '  gdrive-sections, screenshot, fetch-image, image-meta,',
    '  image-text, resume, replace, insert-section, pr-slice,',
    '  sharepoint-resolve, transcript, transcript-outline, video-chapters,',
    '  write-file, zip-list, zip-read, mcp-history, compact-doc, compact-hint,',
    '  conflicts, prune-cache',
    '',
    'Tip: look up one command instead of this whole list: \'token-goat help <command>\', or \'token-goat commands --grep <pattern>\' anchored (\'^read$\' ~700B; bare \'read\' matches descriptions too, ~7KB).',
    '',
  ]
  return lines.join('\n')
}
