/**
 * A minimal Model Context Protocol server, in-house.
 *
 * This replaces `@modelcontextprotocol/sdk` on the shipping path. The SDK is excellent and
 * Anthropic-maintained, but it is built to be every MCP participant at once -- client and server,
 * stdio and HTTP and SSE, OAuth, resources, prompts, completions, sampling, elicitation, tasks --
 * and it charges every install for all of it. It brings 91 packages, among them *two* HTTP
 * frameworks (`express` and `hono`), `cors`, `body-parser`, `express-rate-limit`, `jose`,
 * `pkce-challenge`, `qs` and `path-to-regexp`. Token-goat runs one stdio server that registers
 * tools and answers `tools/call`. It reaches none of the HTTP surface, so none of those packages
 * can ever execute here; they are pure install weight and pure supply-chain surface.
 *
 * What token-goat actually used of the SDK is small enough to state in full: `new McpServer(info)`,
 * `registerTool(name, {description, inputSchema}, handler)`, `connect(transport)`, `close()`, and
 * an `onclose` callback. That is what this file implements, plus the four protocol methods a
 * tools-only server has to answer (`initialize`, `ping`, `tools/list`, `tools/call`) and the
 * notifications it has to tolerate.
 *
 * **The SDK stays a devDependency, and that is the point.** Every MCP test in this repository
 * drives this server through the SDK's own `Client` over its own `InMemoryTransport`. So the
 * reference implementation -- schema validation, JSON-RPC framing, capability assertions,
 * protocol-version negotiation and all -- is the thing checking our wire format on every run. A
 * hand-written fake of the client would prove nothing; the real one proves interoperability.
 *
 * **Deliberately not implemented**, because token-goat registers none of them and a stub that
 * answers a method it cannot serve is worse than a clean `Method not found`: resources, prompts,
 * completions, logging, sampling, elicitation, roots, tasks, progress notifications, request
 * cancellation, and every transport other than stdio. Capabilities advertise `tools` only, so a
 * conforming client never asks -- the SDK's own client refuses to send `resources/list` to a
 * server that did not declare `resources`.
 *
 * Wire-format decisions worth stating, because each was read off the reference implementation
 * rather than guessed:
 *
 * - `initialize` echoes the client's requested protocol version when we recognise it, and falls
 *   back to our own latest when we do not. That is the spec's negotiation rule, and it is what
 *   keeps an older client working instead of being told a version it will reject.
 * - `inputSchema` is JSON Schema generated by `z.toJSONSchema(..., {io: 'input'})`, with `$schema`
 *   forced to the draft-07 identifier the SDK emits. Zod's own default is the 2020-12 identifier,
 *   which is what the MCP spec names, but changing the string a shipped server sends is a
 *   behaviour change, and this change is meant to remove packages, not to alter output. The
 *   generated schemas are identical under either draft.
 * - A tool handler that throws becomes `{isError: true}` with the message as text, not a JSON-RPC
 *   error. That is what the SDK does, and it matters: a JSON-RPC error is a protocol failure the
 *   client raises, while `isError` is a tool result the model can read and react to.
 * - Argument validation failures take the same path, so a bad argument reaches the model as a
 *   readable message rather than killing the call.
 */

import { z } from 'zod'

/** The version this server speaks natively. */
export const LATEST_PROTOCOL_VERSION = '2025-11-25'

/**
 * Versions this server will negotiate down to. Mirrors the SDK's list: a client asking for any of
 * these gets its own version echoed back, which is what the spec asks for and what stops a client
 * pinned to an older revision from refusing the handshake.
 */
export const SUPPORTED_PROTOCOL_VERSIONS = [
  LATEST_PROTOCOL_VERSION,
  '2025-06-18',
  '2025-03-26',
  '2024-11-05',
  '2024-10-07',
] as const

/** JSON-RPC 2.0 error codes, the subset a tools-only server can produce. */
export const JSONRPC_INVALID_REQUEST = -32600
export const JSONRPC_METHOD_NOT_FOUND = -32601
export const JSONRPC_INVALID_PARAMS = -32602

/** A JSON-RPC id: the spec allows a string or a number, and never an object. */
export type JsonRpcId = string | number

export interface JsonRpcRequest {
  jsonrpc: '2.0'
  id: JsonRpcId
  method: string
  params?: Record<string, unknown>
}

export interface JsonRpcNotification {
  jsonrpc: '2.0'
  method: string
  params?: Record<string, unknown>
}

export interface JsonRpcResponse {
  jsonrpc: '2.0'
  id: JsonRpcId
  result: Record<string, unknown>
}

export interface JsonRpcErrorResponse {
  jsonrpc: '2.0'
  id: JsonRpcId
  error: { code: number; message: string; data?: unknown }
}

export type JsonRpcMessage = JsonRpcRequest | JsonRpcNotification | JsonRpcResponse | JsonRpcErrorResponse

/**
 * The transport contract, duck-typed so the SDK's own `InMemoryTransport` satisfies it without
 * any adapter -- that is what lets the tests keep driving this server with the reference client.
 */
export interface McpTransport {
  start(): Promise<void>
  send(message: JsonRpcMessage): Promise<void>
  close(): Promise<void>
  // `| undefined` on each, rather than `?` alone, because this repo compiles with
  // exactOptionalPropertyTypes: without it an implementation that declares the field as possibly
  // unset does not satisfy the interface, and the SDK's own transports declare exactly that.
  onmessage?: ((message: JsonRpcMessage) => void) | undefined
  onclose?: (() => void) | undefined
  onerror?: ((error: Error) => void) | undefined
}

/** The tool result shape, matching the SDK's `CallToolResult` for the subset token-goat returns. */
export interface CallToolResult {
  content: { type: 'text'; text: string }[]
  isError?: boolean
}

/** A zod object shape, the same thing the SDK's `registerTool` takes as `inputSchema`. */
export type ToolInputShape = Record<string, z.ZodType>

export interface ToolDefinition<Shape extends ToolInputShape = ToolInputShape> {
  description?: string
  inputSchema?: Shape
}

/** The argument object a handler receives, inferred from the shape it registered. */
export type ToolArgs<Shape extends ToolInputShape> = z.infer<z.ZodObject<Shape>>

/**
 * The stored form. Registration is generic and erases to this, which is why `registerTool` casts
 * once at the boundary: the cast is the single point where the per-tool type is traded for a
 * uniform map entry, and the schema that validated the arguments is the thing that makes it sound.
 */
type ErasedHandler = (args: unknown) => CallToolResult | Promise<CallToolResult>

interface RegisteredTool {
  name: string
  description: string | undefined
  /** Pre-built so `tools/list` never pays for schema generation, however often it is called. */
  jsonSchema: Record<string, unknown>
  validator: z.ZodType
}

/**
 * The `$schema` identifier the SDK emits for tool input schemas. Zod defaults to the 2020-12
 * identifier; we pin the SDK's so a client that inspects this field sees no change from the
 * version of token-goat that used the SDK directly.
 */
const DRAFT_07_SCHEMA_ID = 'http://json-schema.org/draft-07/schema#'

/**
 * A wart, preserved deliberately.
 *
 * The SDK raises bad-argument and unknown-tool failures as an `McpError`, catches it, and puts
 * `error.message` into the tool result -- and `McpError`'s message begins `MCP error -32602: `.
 * So that prefix has always been on the wire, in text a model reads, even though it is an internal
 * error class leaking into a user-facing string. This commit removes packages; it does not change
 * output. Dropping the prefix would be an improvement worth making on its own, where it is visible.
 */
const MCP_INVALID_PARAMS_PREFIX = `MCP error ${JSONRPC_INVALID_PARAMS}: `

/** What a tool with no declared arguments advertises. Matches the SDK's `EMPTY_OBJECT_JSON_SCHEMA`. */
const EMPTY_OBJECT_JSON_SCHEMA = { type: 'object', properties: {} }

function buildJsonSchema(shape: ToolInputShape | undefined): Record<string, unknown> {
  if (shape === undefined || Object.keys(shape).length === 0) return { ...EMPTY_OBJECT_JSON_SCHEMA }
  const schema = z.toJSONSchema(z.object(shape), { io: 'input' }) as Record<string, unknown>
  return { ...schema, $schema: DRAFT_07_SCHEMA_ID }
}

/**
 * Renders a zod failure exactly the way the SDK's `getParseErrorMessage` and `getDotPath` do:
 * `message at path` per issue, newline-joined, with a bare message when the issue has no path, and
 * `a.b[0].c` addressing for nested fields.
 *
 * Matched character for character on purpose. This text reaches the model as the tool's answer, so
 * it is output, and a change here would be a behaviour change smuggled into a dependency removal.
 */
function describeParseError(error: z.ZodError): string {
  return error.issues
    .map((issue) => {
      if (issue.path.length === 0) return issue.message
      const dotted = issue.path.reduce<string>(
        (acc, seg, i) => (i === 0 ? String(seg) : typeof seg === 'number' ? `${acc}[${seg}]` : `${acc}.${String(seg)}`),
        '',
      )
      return `${issue.message} at ${dotted}`
    })
    .join('\n')
}

function errorText(message: string): CallToolResult {
  return { content: [{ type: 'text', text: message }], isError: true }
}

function isRequest(message: JsonRpcMessage): message is JsonRpcRequest {
  return 'method' in message && 'id' in message && message.id !== undefined && message.id !== null
}

/**
 * A tools-only MCP server.
 *
 * Handlers are registered up front and never change, so there is no `notifications/tools/list_changed`
 * and the `tools` capability declares no `listChanged`.
 */
export class McpServer {
  private readonly info: { name: string; version: string }
  private readonly tools = new Map<string, RegisteredTool>()
  private readonly handlers = new Map<string, ErasedHandler>()
  private transport: McpTransport | undefined
  /** Set by the caller to learn when the peer hung up; `mcp-serve` waits on exactly this. */
  onclose: (() => void) | undefined

  constructor(info: { name: string; version: string }) {
    this.info = info
  }

  /**
   * Registers a tool. Schema generation happens here rather than at `tools/list` time, which also
   * means a malformed shape fails loudly at startup instead of on a client's first listing.
   */
  registerTool<Shape extends ToolInputShape = Record<string, never>>(
    name: string,
    definition: ToolDefinition<Shape>,
    handler: (args: ToolArgs<Shape>) => CallToolResult | Promise<CallToolResult>,
  ): void {
    if (this.tools.has(name)) throw new Error(`MCP tool registered twice: ${name}`)
    const shape = definition.inputSchema
    this.tools.set(name, {
      name,
      description: definition.description,
      jsonSchema: buildJsonSchema(shape),
      // An absent shape still needs a validator, so an argumentless tool called with arguments is
      // not silently handed them.
      validator: z.object(shape ?? {}),
    })
    this.handlers.set(name, handler as ErasedHandler)
  }

  /**
   * Wires this server to a transport and starts it.
   *
   * `onmessage` is assigned before `start()` on purpose: a transport may have buffered messages
   * that arrive the moment it starts (the SDK's in-memory transport queues anything sent before a
   * handler exists and drains the queue inside `start()`), so a server that started first would
   * drop the client's `initialize`.
   */
  async connect(transport: McpTransport): Promise<void> {
    this.transport = transport
    transport.onmessage = (message) => {
      void this.handleMessage(message)
    }
    transport.onclose = () => {
      this.transport = undefined
      this.onclose?.()
    }
    await transport.start()
  }

  async close(): Promise<void> {
    const transport = this.transport
    this.transport = undefined
    await transport?.close()
  }

  private async send(message: JsonRpcMessage): Promise<void> {
    // A peer that vanished mid-request is a normal shutdown race, not an error worth surfacing:
    // the client is gone, so there is nobody left to tell.
    try {
      await this.transport?.send(message)
    } catch {
      /* peer gone */
    }
  }

  private async handleMessage(message: JsonRpcMessage): Promise<void> {
    // One check, and it is the whole rule: only a message carrying an id gets a reply.
    //
    // That covers both things we drop. Responses to requests we never send have an id but no
    // method. Notifications (`initialized`, `cancelled`, and whatever a future client adds) have a
    // method but no id, and the JSON-RPC spec forbids replying to one at all -- so an unknown
    // notification must be dropped silently rather than answered with "method not found", which is
    // the mistake a `default:` branch invites. There was a separate `isNotification` guard above
    // this line; it was removed because it could never fire, since a notification fails the id test
    // anyway, and a branch that cannot fire is not a guard however much it reads like one.
    if (!isRequest(message)) return
    const { id, method } = message
    const params = (message.params ?? {}) as Record<string, unknown>
    try {
      switch (method) {
        case 'initialize':
          await this.send({ jsonrpc: '2.0', id, result: this.initializeResult(params) })
          return
        case 'ping':
          await this.send({ jsonrpc: '2.0', id, result: {} })
          return
        case 'tools/list':
          await this.send({ jsonrpc: '2.0', id, result: { tools: this.listTools() } })
          return
        case 'tools/call':
          await this.send({ jsonrpc: '2.0', id, result: (await this.callTool(params)) as unknown as Record<string, unknown> })
          return
        default:
          await this.sendError(id, JSONRPC_METHOD_NOT_FOUND, `Method not found: ${method}`)
          return
      }
    } catch (err) {
      // Reaching here means the dispatch itself failed, not the tool: a tool's own failure is
      // already turned into an isError result inside callTool.
      await this.sendError(id, JSONRPC_INVALID_REQUEST, err instanceof Error ? err.message : String(err))
    }
  }

  private async sendError(id: JsonRpcId, code: number, message: string): Promise<void> {
    await this.send({ jsonrpc: '2.0', id, error: { code, message } })
  }

  private initializeResult(params: Record<string, unknown>): Record<string, unknown> {
    const requested = params['protocolVersion']
    const protocolVersion =
      typeof requested === 'string' && (SUPPORTED_PROTOCOL_VERSIONS as readonly string[]).includes(requested)
        ? requested
        : LATEST_PROTOCOL_VERSION
    return {
      protocolVersion,
      // Tools only, and they never change after startup, so no `listChanged`. This is the one
      // place we deliberately do not copy the SDK, which declares `listChanged: true` because its
      // McpServer is *able* to send that notification. Token-goat registers every tool before it
      // connects and never adds or removes one, so we would be promising a notification we can
      // never have cause to send. No client behaviour turns on it either way -- a subscription
      // that never fires and an absent subscription are the same thing when the list is fixed --
      // so the honest declaration wins. Contrast the tool-error text below, which a model reads as
      // content and is therefore matched to the SDK exactly.
      capabilities: { tools: {} },
      serverInfo: { name: this.info.name, version: this.info.version },
    }
  }

  private listTools(): Record<string, unknown>[] {
    return [...this.tools.values()].map((tool) => ({
      name: tool.name,
      ...(tool.description !== undefined ? { description: tool.description } : {}),
      inputSchema: tool.jsonSchema,
      // The SDK emits this for every tool it registers, and it is literally true of ours: we do
      // not implement task augmentation, so a client that asks for it gets refused. Emitting the
      // same thing keeps `tools/list` byte-identical to what token-goat sent before, which is what
      // the differential test in tests/mcp_jsonrpc.test.ts pins.
      execution: { taskSupport: 'forbidden' },
    }))
  }

  private async callTool(params: Record<string, unknown>): Promise<CallToolResult> {
    const name = params['name']
    if (typeof name !== 'string') return errorText('Invalid params: tools/call requires a string "name"')
    const tool = this.tools.get(name)
    const handler = this.handlers.get(name)
    if (tool === undefined || handler === undefined) return errorText(`${MCP_INVALID_PARAMS_PREFIX}Tool ${name} not found`)
    const parsed = tool.validator.safeParse(params['arguments'] ?? {})
    if (!parsed.success) {
      return errorText(
        `${MCP_INVALID_PARAMS_PREFIX}Input validation error: Invalid arguments for tool ${name}: ${describeParseError(parsed.error)}`,
      )
    }
    try {
      return await handler(parsed.data)
    } catch (err) {
      return errorText(err instanceof Error ? err.message : String(err))
    }
  }
}
