"""Lightweight bash-filter detection module — no regex compilation.

Provides a single function, :func:`detect`, that answers "does bash_compress
have a filter for this command?" using a static binary→filter_name lookup
table.  This module imports in <1 ms (vs ~75 ms for bash_compress which
compiles 737+ regexes at module load time).

The hook layer imports this module on every Bash pre-hook invocation to decide
whether to proceed with compression.  Only when a filter IS found does the hook
import the full bash_compress module; unrecognised commands pay zero regex cost.

The table is generated from bash_compress.FILTERS at development time.  Update
it when filters are added or removed from that list.
"""

from __future__ import annotations

from pathlib import Path

# Maps binary stem (lowercased) to the name of the first-matching filter in
# bash_compress.FILTERS.  First-match semantics mirror select_filter() so the
# detection result is consistent with what full compression would use.
# Generated from bash_compress.FILTERS (134 filters, 229 binaries).
_BINARY_TO_FILTER: dict[str, str] = {
    "./gradlew": "gradle",
    "./mvnw": "maven",
    "@biomejs/biome": "biome",
    "ack": "grep",
    "ack-grep": "grep",
    "act": "act",
    "ag": "grep",
    "aider": "aider",
    "ansible": "ansible",
    "ansible-console": "ansible",
    "ansible-galaxy": "ansible",
    "ansible-lint": "ansible",
    "ansible-playbook": "ansible",
    "ansible-pull": "ansible",
    "ant": "ant",
    "apk": "sys-pkg",
    "apt": "sys-pkg",
    "apt-cache": "sys-pkg",
    "apt-get": "sys-pkg",
    "ava": "jest",
    "aws": "aws-cli",
    "aws2": "aws-cli",
    "az": "azure-cli",
    "bandit": "bandit",
    "bat": "bat",
    "batcat": "bat",
    "bazel": "bazel",
    "bazelisk": "bazel",
    "biome": "biome",
    "black": "black-isort",
    "brew": "sys-pkg",
    "buck": "make",
    "buf": "protoc",
    "buildah": "docker",
    "bun": "bun",
    "bundle": "bundler",
    "bundler": "bundler",
    "bunx": "bun",
    "cabal": "haskell",
    "cargo": "dep-list",
    "ccmake": "cmake",
    "cdk": "cdk",
    "clang-tidy": "clang-tidy",
    "claude": "claude-cli",
    "claude-dev": "cline",
    "cline": "cline",
    "cmake": "cmake",
    "cypress": "cypress",
    "colordiff": "diff",
    "composer": "composer",
    "composer.phar": "composer",
    "conan": "conan",
    "conan2": "conan",
    "codex": "codex-exec",
    "conda": "conda",
    "continue": "continue",
    "copilot": "copilot",
    "cpack": "cmake",
    "cppcheck": "cppcheck",
    "crystal": "crystal",
    "ctest": "cmake",
    "curl": "curl",
    "cursor": "cursor",
    "dart": "dart",
    "delta": "delta",
    "deno": "deno",
    "diff": "diff",
    "diff3": "diff",
    "dmypy": "mypy",
    "docker": "docker-compose",
    "docker-compose": "docker-compose",
    "dotnet": "dotnet",
    "egrep": "grep",
    "elm": "elm",
    "esbuild": "webpack",
    "eslint": "eslint",
    "exa": "eza",
    "eza": "eza",
    "fd": "fd",
    "fdfind": "fd",
    "fgrep": "grep",
    "find": "fd",  # plain-path output matches fd; -ls/-printf formats truncated at line boundaries
    "flutter": "flutter",
    "fly": "fly",
    "flyctl": "fly",
    "forge": "forge",
    "fzf": "fzf",
    "gcloud": "gcloud",
    "gem": "gem",
    "gemini": "gemini-cli",
    "gh": "gh-copilot",
    "ghc": "haskell",
    "git": "git-log",
    "gmake": "make",
    "go": "go-test",
    "goimports": "make",
    "golangci-lint": "golangci-lint",
    "gradle": "gradle",
    "gradlew": "gradle",
    "grep": "grep",
    "hardhat": "hardhat",
    "helm": "helm",
    "isort": "black-isort",
    "javac": "javac",
    "jest": "jest",
    "jq": "jq",
    "julia": "julia",
    "k": "kubectl-logs",
    "k9s": "kubectl",
    "ktlint": "ktlint",
    "kubectl": "kubectl-logs",
    "lazygit": "lazygit",
    "lerna": "lerna",
    "lessc": "sass",
    "ls": "eza",
    "make": "make",
    "mamba": "conda",
    "maven": "make",
    "meson": "meson",
    "micromamba": "conda",
    "minitest": "ruby",
    "mix": "mix",
    "mocha": "jest",
    "msbuild": "msbuild",
    "msbuild.exe": "msbuild",
    "mvn": "maven",
    "mvnw": "maven",
    "mypy": "mypy",
    "mysql": "mysql",
    "mysqldump": "mysql",
    "nerdctl": "docker",
    "ninja": "make",
    "nix": "nix",
    "nix-build": "nix",
    "nix-env": "nix",
    "nix-shell": "nix",
    "nix-store": "nix",
    "nixos-rebuild": "nix",
    "node": "node",
    "node-sass": "sass",
    "nodejs": "node",
    "npm": "npm_install",
    "npx": "nx",
    "nuget": "nuget",
    "nuget.exe": "nuget",
    "nx": "nx",
    "oc": "kubectl",
    "opencode": "opencode",
    "oxc_linter": "oxlint",
    "oxlint": "oxlint",
    "packer": "packer",
    "phpstan": "phpstan",
    "phpstan.phar": "phpstan",
    "pip": "dep-list",
    "pip3": "dep-list",
    "pipx": "pip",
    "playwright": "playwright",
    "poetry": "dep-list",
    "pnpm": "npm_install",
    "pnpx": "nx",
    "podman": "docker",
    "powershell": "powershell",
    "powershell.exe": "powershell",
    "pre-commit": "pre-commit",
    "prettier": "prettier",
    "protoc": "protoc",
    "protoc-gen-go": "protoc",
    "protoc-gen-grpc": "protoc",
    "psalm": "phpstan",
    "psalm.phar": "phpstan",
    "psql": "psql",
    "pub": "pub",
    "pulumi": "pulumi",
    "pwsh": "powershell",
    "py.test": "pytest",
    "pylint": "pylint",
    "pyright": "linter",
    "pytest": "pytest",
    "python": "python",
    "python3": "python",
    "python3.11": "python",
    "python3.12": "python",
    "python3.13": "python",
    "r": "r-cmd",
    "rake": "ruby",
    "rebar": "rebar3",
    "rebar3": "rebar3",
    "redis-cli": "redis-cli",
    "rg": "grep",
    "rome": "linter",
    "rscript": "r-cmd",
    "rspec": "ruby",
    "rspec2": "ruby",
    "rsync": "rsync",
    "ruby": "ruby",
    "ruff": "ruff",
    "run-clang-tidy": "clang-tidy",
    "run-clang-tidy.py": "clang-tidy",
    "runghc": "haskell",
    "runhaskell": "haskell",
    "sass": "sass",
    "sbt": "sbt",
    "scss": "sass",
    "sdiff": "diff",
    "semgrep": "semgrep",
    "serverless": "serverless",
    "shards": "crystal",
    "sls": "serverless",
    "snyk": "snyk",
    "sqlite3": "sqlite3",
    "stack": "haskell",
    "stylelint": "linter",
    "swift": "swift",
    "swiftlint": "swiftlint",
    "tap": "jest",
    "terraform": "terraform",
    "terragrunt": "terraform",
    "tofu": "terraform",
    "tox": "tox",
    "tree": "tree",
    "trivy": "trivy",
    "tsc": "linter",
    "turbo": "turbo",
    "uv": "dep-list",
    "vault": "vault",
    "vcpkg": "vcpkg",
    "vite": "webpack",
    "vitest": "vitest",
    "wasm-pack": "wasm-pack",
    "wc": "wc",
    "wdiff": "diff",
    "wget": "curl",
    "windsurf": "windsurf",
    "webpack": "webpack",
    "webpack-cli": "webpack",
    "wrangler": "wrangler",
    "wrangler2": "wrangler",
    "xcodebuild": "xcode",
    "yarn": "npm_install",
    "yq": "yq",
    "zig": "zig",
}


def detect(argv: list[str]) -> str | None:
    """Return the filter name for *argv*, or ``None`` if no filter matches.

    Checks the binary stem (``Path(argv[0]).stem.lower()``) against the static
    lookup table.  Returns the filter name string (e.g. ``"pytest"``) when a
    match is found, ``None`` otherwise.

    This function intentionally does NOT check subcommands — that finer
    discrimination is left to bash_compress.select_filter() which is only
    called when this function confirms a filter exists for the binary.
    """
    if not argv:
        return None
    stem = Path(argv[0].replace("\\", "/")).stem.lower()
    return _BINARY_TO_FILTER.get(stem)
